version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"     
  header: '![](toolchain.svg?localize)'
toolchain:
  template:
    v1-projectId: '{{projectId}}'
    scheduledDate: '{{scheduledDate}}'
    getting_started:
      $ref: "#/messages/template.gettingStarted"
  name: '{{projectName}}'
  required:
    - deploy
    - repo
  generator: migration-engine
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: '{{projectName}}'
      repo_url: '{{projectRepoUrl}}'
      type: link
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{projectName}}'
      v1-projectId: '{{projectId}}'
      configuration:
        content: '{{pipelineContent}}'
        execute: false
        env:
          REPO: repo
        source:
          version: v1
          environment: '{{pipelineEnv}}'
          pipelineUrl: '{{pipelineUrl}}'
          projectUrl: '{{projectUrl}}'
          showLink: true
  webide:
    service_id: orion
form:
  githubpublic:
    parameters:
      repo_url: '{{projectRepoUrl}}'
    schema:
      $ref: github.json
